version: '3'
services:
  node: 
    image: 'node:10-alpine3.9'
    container_name: 'portfolio-of-panuwat'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    command: 'yarn install && yarn start' 
      